
let products = {
    data: [
        {
            id: 1,
            productName: "RTX 4070 TI",
            completeName: "ASUS GeForce TUF Gaming RTX 4070Ti 12GB",
            category: "Graphic-Card",
            price: "780 USD",
            image: "../img/3.webp",
            reviews: "(75)",
            total: "100",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/rtx4070ti/40701.webp",
                "../img/pics/rtx4070ti/40702.webp",
                "../img/pics/rtx4070ti/40703.webp",
                "../img/pics/rtx4070ti/40704.webp",
            ],
            details: [
                "Chispet: RTX 4070 Ti",
                "Hdmi ports: 1",
                "Vga ports: 0",
                "Displayports: 3",
                "Pcie 16 pins: 1",
                "Pcie 6 pins: 0",
                "Pcie 8 pins: 0",
                "Usage: 250 w",
                "Minimum watts: 650 w",
                "Base core speed: 2520 mhz",
                "Memory speed: 21000 mhz",
                "Memory capacity: 12 gb",
                "Memory type: GDDR6X",
                "Width: 120 mm",
                "Length: 308 mm",
                "Thickness: 2.5 slots",
            ],
            description: "The ASUS GeForce TUF Gaming RTX 4070 Ti 12GB is a powerhouse graphics card designed for serious gamers and content creators. Featuring the latest RTX 4070 Ti chipset, it delivers stunning visuals and smooth performance with 12GB of GDDR6X memory. With a robust cooling system and advanced technologies like ray tracing and AI-enhanced graphics, this card ensures high frame rates and immersive gaming experiences. Ideal for 4K gaming, VR, and demanding applications, the RTX 4070 Ti combines power and efficiency, making it a top choice for high-end gaming rigs.",
        },
        {
            id: 2,
            productName: "LOGITECH G PRO",
            completeName: "Logitech G PRO Lightweight Wireless",
            category: "Mouse",
            price: "53 USD",
            image: "../img/2.webp",
            reviews: "(452)",
            total: "525",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/gpro/gpro1.webp",
                "../img/pics/gpro/logi2.jpg",
                "../img/pics/gpro/logi3.jpg",
            ],
            details: [
                "Color: Black",
                "Buttons: 5",
                "Switch: Omron",
                "Sensor type: Optic",
                "Sensor: Hero 25K",
                "Wireless: Yes",
                "Minimum DPI: 100",
                "Maximum DPI: 25600",
                "Response frequency: 1000 hz",
                "Maximum speed: 400 ips",
                "Maximum acceleration: 40 G",
                "Wifi technology: Lightspeed",
                "Weight: 63 gr",
                "Weight system: No",
                "Width: 63.5 mm",
                "Depth: 125mm",
                "Height: 40mm",
            ],
            description: "The Logitech G Pro Wireless is a top-tier gaming mouse engineered for esports professionals. Weighing just 80 grams, it offers unparalleled speed and precision with its HERO 25K sensor and a DPI range of up to 25,600. The ambidextrous design and removable side buttons make it highly customizable for any grip style. With up to 60 hours of battery life and a reliable 1 ms report rate, it ensures consistent performance during intense gaming sessions. The G Pro Wireless combines lightweight design, cutting-edge technology, and professional-grade performance.",
        },
        {
            id: 3,
            productName: "RX 7900 GRE",
            completeName: "Radeon RX 7900 GRE OC Edition 16GB GDDR6",
            category: "Graphic-Card",
            price: "590 USD",
            image: "../img/5.webp",
            reviews: "(105)",
            total: "133",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/rx7900gre/79001.webp",
                "../img/pics/rx7900gre/79002.webp",
                "../img/pics/rx7900gre/79003.jpg",
            ],
            details: [
                "Chispet: RX 7900 GRE",
                "Hdmi ports: 1",
                "Vga ports: 0",
                "Displayports: 3",
                "Pcie 16 pins: 0",
                "Pcie 6 pins: 0",
                "Pcie 8 pins: 2",
                "Usage: 350 w",
                "Minimum watts: 750 w",
                "Base core speed: 2175 mhz",
                "Memory speed: 20000 mhz",
                "Memory capacity: 20 gb",
                "Memory type: GDDR6",
                "Width: 120mm",
                "Length: 340mm",
                "Thickness: 3 slots",
            ],
            description: "The RX 7900 GRE is a cutting-edge graphics card built for exceptional gaming and content creation. Powered by AMD's RDNA 3 architecture, it features 16GB of GDDR6 memory and delivers impressive performance across all modern titles. With support for ray tracing and advanced AI capabilities, the RX 7900 GRE offers realistic lighting, shadows, and reflections. Its robust cooling solution ensures stable performance under heavy loads. Ideal for 4K gaming and VR, this card is perfect for enthusiasts seeking top-notch visuals and performance.",
        },
        {
            id: 4,
            productName: "LOGITECH G355",
            completeName: "Logitech G335 Wired Gaming Headset",
            category: "Headset",
            price: "57 USD",
            image: "../img/1.webp",
            reviews: "(98)",
            total: "102",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/g355/g3551.jepg",
                "../img/pics/g355/g3552.jpg",
                "../img/pics/g355/g3553.jpg",
            ],
            details: [
                "Model: G335",
                "Color: White",
                "Microphone: Yes",
                "Monoaural: No",
                "Wireless: No",
                "Wire lenght USB-A: 2.1m",
                "Wire lenght USB-C: -",
                "Wire lenght 3.5mm: -",
            ],
            description: "The Logitech G335 is a lightweight and comfortable gaming headset perfect for long gaming sessions. Weighing just 240 grams, it features soft memory foam ear cushions and an adjustable suspension headband for a personalized fit. The 40mm neodymium drivers deliver clear and immersive sound, while the flip-to-mute microphone ensures clear communication. Compatible with multiple platforms, including PC, console, and mobile, the G335 offers vibrant color options and reliable performance for gamers of all levels.",
        },
        {
            id: 5,
            productName: "RYZEN 5 5600",
            completeName: "AMD Ryzen 5 5600 6-Core 3.5 GHz Socket AM4",
            category: "Processor",
            price: "133 USD",
            image: "../img/6.webp",
            reviews: "(755)",
            total: "844",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/r55600/56001.webp",
                "../img/pics/r55600/56002.webp",
                "../img/pics/r55600/56003.jpg",
            ],
            details: [
                "Model: 5600",
                "Socket: AM4 Ryzen 4th Gen",
                "Cores: 6",
                "Threads: 12",
                "Frequency: 3500 mhz",
                "Manufacturing process: 7 nm",
                "GPU Chispet: No",
                "Turbo frequency: 4400 mhz",
                "Family: Ryzen 5",
                "TDP: 65 w",
                "Cooler included: Yes",
                "L1 memory: 0",
                "L2 memory: 3 mb",
                "L3 memory: 32 mb",
            ],
            description: "The Ryzen 5 5600 is a powerful six-core processor from AMD, ideal for gaming and multitasking. Built on the advanced Zen 3 architecture, it offers a base clock speed of 3.7 GHz and a boost clock of up to 4.6 GHz. With 12 threads and support for PCIe 4.0, it delivers excellent performance and responsiveness. The Ryzen 5 5600 is perfect for building a high-performance gaming PC or a productivity workstation, offering a balance of power, efficiency, and affordability.",
        },
        {
            id: 6,
            productName: "GT 1030",
            completeName: "GIGABYTE GeForce GT 1030 Low Profile D4 2G",
            category: "Graphic-Card",
            price: "64 USD",
            image: "../img/4.webp",
            reviews: "(34)",
            total: "65",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/gt1030/10301.webp",
                "../img/pics/gt1030/10302.webp",
                "../img/pics/gt1030/10303.webp",
            ],
            details: [
                "Chispet: GT 1030",
                "Hdmi ports: 1",
                "Vga ports: 0",
                "Displayports: 0",
                "Pcie 16 pins: 0",
                "Pcie 6 pins: 0",
                "Pcie 8 pins: 0",
                "Usage: 140 w",
                "Minimum watts: 300 w",
                "Base core speed: 902 mhz",
                "Memory speed: 5010 mhz",
                "Memory capacity: 2 gb",
                "Memory type: GDDR5",
                "Width: 70 mm",
                "Length: 170 mm",
                "Thickness: 2 slots",
            ],
            description: "The GT 1030 is a budget-friendly graphics card designed for everyday computing and casual gaming. Equipped with 2GB of GDDR5 memory, it provides decent performance for light gaming, multimedia tasks, and HD video playback. Its compact form factor makes it suitable for small builds and HTPCs. The GT 1030 supports DirectX 12 and features efficient cooling for reliable performance. Ideal for upgrading older systems, this card offers a balance of affordability and functionality for basic computing needs.",
        },
        {
            id: 7,
            productName: "Gigabyte B450 V2",
            completeName: "Gigabyte B450 Aorus Elite V2",
            category: "Motherboard",
            price: "117 USD",
            image: "../img/7mother.webp",
            reviews: "(560)",
            total: "720",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/b450/4501.webp",
                "../img/pics/b450/4502.webp",
                "../img/pics/b450/4503.jpg",
            ],
            details: [
                "Model: B450M DS3H",
                "Version: V2",
                "Color: Black",
                "Chipset: AMD B450",
                "Socket: AM4",
                "Ram type: DDR4",
                "Maximum ram memory: 128 GB",
                "Ram modules: 4",
                "SATA port: 4",
                "LAN port: Realtek (1000/100 Mbit)",
                "PCI-E x16 running x16: 1",
                "PCI-E x16 running x4: 1",
            ],
            description: "The Gigabyte B450 V2 is a versatile motherboard designed for AMD Ryzen processors. Featuring support for DDR4 memory up to 3600 MHz, it ensures fast and stable performance. The board offers multiple connectivity options, including USB 3.1, HDMI, and M.2 slots for high-speed storage. With robust power delivery and advanced cooling solutions, the B450 V2 is ideal for building reliable and efficient gaming or productivity systems. It also supports RGB lighting, allowing for customizable aesthetics.",
        },
        {
            id: 8,
            productName: "MSI B760 PLUS",
            completeName: "MSI B760 GAMING PLUS",
            category: "Motherboard",
            price: "163 USD",
            image: "../img/8mother.jpg",
            reviews: "(265)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/b760/7601.jpg",
                "../img/pics/b760/7602.jpg",
                "../img/pics/b760/7603.jpg",
            ],
            details: [
                "Model: B760 GAMING PLUS WIFI",
                "Version: WiFi",
                "Color: Black",
                "Chipset: B760",
                "Socket: 1700",
                "Ram type: DDR5",
                "Maximum ram memory: 192 GB",
                "Ram modules: 4",
                "SATA port: x4 SATA-3",
                "LAN port: Realtek RTL8125BG 2.5G",
                "PCI-E x16 running x16: 5",
                "PCI-E x16 running x4: -",
            ],
            description: "The MSI B760 PLUS is a high-performance motherboard designed for Intel's latest processors. It supports DDR5 memory and features PCIe 5.0 slots for the latest GPUs and SSDs. With enhanced power delivery and advanced cooling solutions, it ensures stable and efficient performance under heavy loads. The motherboard offers multiple connectivity options, including USB 3.2 Gen 2x2, Wi-Fi 6, and 2.5G LAN. Ideal for gamers and content creators, the B760 PLUS combines cutting-edge technology with robust build quality.",
        },
        {
            id: 9,
            productName: "Intel I5-12400F",
            completeName: "I5-12400F - 6-Core 2.5 GHz - LGA 1700",
            category: "Processor",
            price: "133 USD",
            image: "../img/9proc.webp",
            reviews: "(1575)",
            total: "1800",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/i512400f/12400f1.webp",
                "../img/pics/i512400f/12400f2.webp",
                "../img/pics/i512400f/12400f3.webp",
            ],
            details: [
                "Model: 12400F",
                "Socket: 1700 Alder Lake-S",
                "Cores: 6",
                "Threads: 12",
                "Frequency: 2500 mhz",
                "Manufacturing process: 10 nm",
                "GPU Chispet: No",
                "Turbo frequency: 4400 mhz",
                "Family: i5",
                "TDP: 65 w",
                "Cooler included: Yes",
                "L1 memory: 0.48 mb",
                "L2 memory: 7.5 mb",
                "L3 memory: 18 mb",
            ],
            description: "The Intel I5-12400F is a powerful mid-range processor ideal for gaming and productivity. Featuring six cores and twelve threads, it delivers impressive performance with a base clock speed of 2.5 GHz and a turbo boost up to 4.4 GHz. Built on Intel's 10nm process, it supports PCIe 5.0 and DDR5 memory for future-proofing your system. The I5-12400F offers a great balance of performance and efficiency, making it an excellent choice for budget-conscious gamers and professionals.",
        },
        {
            id: 10,
            productName: "Intel I7-13700K",
            completeName: "i7-13700K - 16-Core 3.4 GHz - LGA 1700",
            category: "Processor",
            price: "389 USD",
            image: "../img/10core.webp",
            reviews: "(262)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/",
                "../img/pics/",
                "../img/pics/",
            ],
            details: [
                "Model: 13700F",
                "Socket: 1700 Raptor Lake",
                "Cores: 16",
                "Threads: 24",
                "Frequency: 2100 mhz",
                "Manufacturing process: 10 nm",
                "GPU Chispet: No",
                "Turbo frequency: 5200 mhz",
                "Family: i7",
                "TDP: 120 w",
                "Cooler included: Yes",
                "L1 memory: 0",
                "L2 memory: 24 mb",
                "L3 memory: 30 mb",
            ],
            description: "The Intel I7-13700K is a high-end processor designed for enthusiasts and power users. With eight cores and sixteen threads, it delivers exceptional performance for gaming, content creation, and multitasking. The base clock speed of 3.6 GHz and turbo boost up to 5.1 GHz ensure blazing-fast responsiveness. Supporting PCIe 5.0 and DDR5 memory, the I7-13700K offers cutting-edge technology for future-proof systems. It's an ideal choice for those seeking top-tier performance and advanced features.",
        },
        {
            id: 11,
            productName: "Kingston FURY 3200MHz 2x8",
            completeName: "RAM Kingston FURY DDR4 3200MHz 16GB 2x8GB",
            category: "Ram",
            price: "54 USD",
            image: "../img/11ram.webp",
            reviews: "(143)",
            total: "400",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/fury3200rgb/fury1.webp",
                "../img/pics/fury3200rgb/fury2.webp",
                "../img/pics/fury3200rgb/fury3.webp",
            ],
            details: [
                "Model: KF432C16BBA/8",
                "Modules: 2",
                "Capacity per module: 8 GB",
                "Color: Black",
                "RGB: Yes",
                "Ram technology: DDR4 SDRAM",
                "Ram speed: 3200 MHz",
                "Pins: 288",
                "Transfer rate: 25600 MB/s",
                "Supply voltage: 1.35V",
            ],
            description: "The Kingston Fury 3200Mhz is a high-performance DDR4 memory module designed for gamers and enthusiasts. With a speed of 3200 MHz, it delivers fast and reliable performance for gaming, multitasking, and demanding applications. The sleek heat spreader ensures efficient cooling and enhances the overall aesthetics of your system. Compatible with Intel and AMD platforms, the Kingston Fury provides a perfect blend of speed, stability, and style, making it a great addition to any high-performance PC build.",
        },
        {
            id: 12,
            productName: "Corsair 2300MHz 2x8",
            completeName: "Corsair Vengeance LPX DDR4 2400MHz 16GB 2x8GB",
            category: "Ram",
            price: "45 USD",
            image: "../img/12ram.webp",
            reviews: "(5051)",
            total: "5700",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/corsair2400/corsair1.jpg",
                "../img/pics/corsair2400/corsair2.jpg",
                "../img/pics/corsair2400/corsair3.webp",
            ],
            details: [
                "Model: Cmk16gx4m2e3200c16",
                "Modules: 2",
                "Capacity per module: 8 GB",
                "Color: Black",
                "RGB: No",
                "Ram technology: DDR4 DRAM",
                "Ram speed: 3200 MHz",
                "Pins: 288",
                "Transfer rate: 25600 MB/s",
                "Supply voltage: 1.35V",
            ],
            description: "The Corsair 2300MHz is a reliable DDR4 memory module designed for smooth and efficient performance. With a speed of 2300 MHz, it offers stable performance for everyday computing tasks, gaming, and multitasking. The module features a sleek design with a low-profile heat spreader for effective cooling. Compatible with a wide range of motherboards, the Corsair 2300MHz is an excellent choice for upgrading or building a dependable and responsive system.",
        },
        {
            id: 13,
            productName: "Razer Viper V3",
            completeName: "Razer Viper V3 HyperSpeed 30000 DPI",
            category: "Mouse",
            price: "110 USD",
            image: "../img/13mouse.jpg",
            reviews: "(95)",
            total: "120",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/razerviper3/viper1.webp",
                "../img/pics/razerviper3/viper2.webp",
                "../img/pics/razerviper3/viper3.webp",
            ],
            details: [
                "Color: Black",
                "Buttons: 6",
                "Switch: Optic switch",
                "Sensor type: Optic",
                "Sensor: Focus pro 35K",
                "Wireless: Yes",
                "Minimum DPI: 100 DPI",
                "Maximum DPI: 30000 DPI",
                "Response frequency: 8000 hz",
                "Maximum speed: 750 ips",
                "Maximum acceleration: 70 G",
                "Wifi technology: Razer HyperSpeed Wireless",
                "Weight: 58 gr",
                "Weight system: No",
                "Width: 64 mm",
                "Depth: 127mm",
                "Height: 39.9mm",
            ],
            description: "The Razer Viper V3 is an elite gaming mouse engineered for competitive gaming. Featuring Razer's advanced optical sensor with a DPI range of up to 20,000, it offers precise and responsive tracking. The lightweight design and ambidextrous shape make it suitable for all grip styles. With Razer's Speedflex cable and optical mouse switches, the Viper V3 ensures swift and accurate clicks. The customizable RGB lighting adds a touch of personal style, making it a perfect choice for serious gamers.",
        },
        {
            id: 14,
            productName: "HyperX Cloud Orbit S",
            completeName: "HyperX Cloud Orbit S - 3D Audio Head Tracking",
            category: "Headset",
            price: "362 USD",
            image: "../img/14head.jpg",
            reviews: "(22)",
            total: "30",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/hyperxclouds/cloud1.jpg",
                "../img/pics/hyperxclouds/cloud2.webp",
            ],
            details: [
                "Model: Cloud Orbit S",
                "Color: Black",
                "Microphone: Yes",
                "Monoaural: No",
                "Wireless: Yes",
                "Wire lenght USB-A: 3m",
                "Wire lenght USB-C: 1.5m",
                "Wire lenght 3.5mm: 1.2m",
            ],
            description: "The HyperX Cloud Orbit S is a premium gaming headset offering immersive 3D audio. Equipped with Audeze planar magnetic drivers, it delivers high-fidelity sound with rich detail. The Waves Nx technology provides precise head tracking for a 360-degree audio experience. With comfortable memory foam ear cushions and a detachable noise-canceling microphone, the Cloud Orbit S ensures long-lasting comfort and clear communication. Compatible with multiple platforms, it's perfect for gamers seeking superior audio quality.",
        },
        {
            id: 15,
            productName: "Thermaltake 600W 80 Plus",
            completeName: "Thermaltake Smart Series 600W SLI 80 Plus",
            category: "Power",
            price: "102 USD",
            image: "../img/15power.webp",
            reviews: "(13)",
            total: "17",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/thermaltake600/thermal1.jpg",
                "../img/pics/thermaltake600/thermal2.webp",
                "../img/pics/thermaltake600/thermal3.jpg",
            ],
            details: [
                "Model: SPD-0600",
                "Power output: 600 w",
                "Color: Black",
                "Voltage: 110V/220V",
                "Refrigeration: Air",
                "Voltage protection: Yes",
                "Includes RBG: No",
                "HDD connectors: 3",
                "SATA connectors: 6",
                "Floppy connectors: 1",
                "PCI-E connectors: 1",
                "Efficency certification: 80 Plus",
                "Fan diameter: 12 mm",
                "Width: 160 mm",
                "Depth: 150 mm",
                "Height: 86 mm",
                "Weight: 1.2 kg",
                "Frequency: 63 Hz",
            ],
            description: "The Thermaltake 600W 80 Plus is a reliable power supply unit designed for efficient and stable performance. With an 80 Plus certification, it ensures high energy efficiency and reduced heat output. The 600W capacity provides ample power for gaming PCs and workstations. Featuring multiple protection mechanisms, including over-voltage, over-current, and short-circuit protection, it guarantees safe and reliable operation. The compact design and quiet fan make it a perfect choice for building a dependable and efficient system.",
        },
    ]
};

export { products };
