
let products = {
    data: [
        {
            id: 1,
            productName: "RTX 4070 TI",
            completeName: "ASUS GeForce TUF Gaming RTX 4070Ti 12GB",
            category: "Graphic-Card",
            price: "780 USD",
            image: "../img/3.webp",
            reviews: "(75)",
            total: "100",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/rtx4070ti/40701.webp",
                "../img/pics/rtx4070ti/40702.webp",
                "../img/pics/rtx4070ti/40703.webp",
                "../img/pics/rtx4070ti/40704.webp",
            ],
        },
        {
            id: 2,
            productName: "LOGITECH G PRO",
            completeName: "Logitech G PRO Lightweight Wireless",
            category: "Mouse",
            price: "53 USD",
            image: "../img/2.webp",
            reviews: "(452)",
            total: "525",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/gpro/gpro1.webp",
                "../img/pics/gpro/logi2.jpg",
                "../img/pics/gpro/logi3.jpg",
            ],
        },
        {
            id: 3,
            productName: "RX 7900 GRE",
            completeName: "Radeon RX 7900 GRE OC Edition 16GB GDDR6",
            category: "Graphic-Card",
            price: "590 USD",
            image: "../img/5.webp",
            reviews: "(105)",
            total: "133",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/rx7900gre/79001.webp",
                "../img/pics/rx7900gre/79002.webp",
                "../img/pics/rx7900gre/79003.jpg",
            ],
        },
        {
            id: 4,
            productName: "LOGITECH G355",
            completeName: "Logitech G335 Wired Gaming Headset",
            category: "Headset",
            price: "57 USD",
            image: "../img/1.webp",
            reviews: "(98)",
            total: "102",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/g355/g3551.jepg",
                "../img/pics/g355/g3552.jpg",
                "../img/pics/g355/g3553.jpg",
            ],
        },
        {
            id: 5,
            productName: "RYZEN 5 5600",
            completeName: "AMD Ryzen 5 5600 6-Core 3.5 GHz Socket AM4",
            category: "Processor",
            price: "133 USD",
            image: "../img/6.webp",
            reviews: "(755)",
            total: "844",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/r55600/56001.webp",
                "../img/pics/r55600/56002.webp",
                "../img/pics/r55600/56003.jpg",
            ],
        },
        {
            id: 6,
            productName: "GT 1030",
            completeName: "GIGABYTE GeForce GT 1030 Low Profile D4 2G",
            category: "Graphic-Card",
            price: "64 USD",
            image: "../img/4.webp",
            reviews: "(34)",
            total: "65",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/gt1030/10301.webp",
                "../img/pics/gt1030/10302.webp",
                "../img/pics/gt1030/10303.webp",
            ],
        },
        {
            id: 7,
            productName: "Gigabyte B450 V2",
            completeName: "Gigabyte B450 Aorus Elite V2",
            category: "Motherboard",
            price: "117 USD",
            image: "../img/7mother.webp",
            reviews: "(560)",
            total: "720",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/b450/4501.webp",
                "../img/pics/b450/4502.webp",
                "../img/pics/b450/4503.jpg",
            ],
        },
        {
            id: 8,
            productName: "MSI B760 PLUS",
            completeName: "MSI B760 GAMING PLUS",
            category: "Motherboard",
            price: "163 USD",
            image: "../img/8mother.jpg",
            reviews: "(265)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/b760/7601.jpg",
                "../img/pics/b760/7602.jpg",
                "../img/pics/b760/7603.jpg",
            ],
        },
        {
            id: 9,
            productName: "Intel I5-12400F",
            completeName: "I5-12400F - 6-Core 2.5 GHz - LGA 1700",
            category: "Processor",
            price: "133 USD",
            image: "../img/9proc.webp",
            reviews: "(1575)",
            total: "1800",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/i512400f/12400f1.webp",
                "../img/pics/i512400f/12400f2.webp",
                "../img/pics/i512400f/12400f3.webp",
            ],
        },
        {
            id: 10,
            productName: "Intel I7-13700K",
            completeName: "i7-13700K - 16-Core 3.4 GHz - LGA 1700",
            category: "Processor",
            price: "389 USD",
            image: "../img/10core.webp",
            reviews: "(262)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/",
                "../img/pics/",
                "../img/pics/",
            ],
        },
        {
            id: 11,
            productName: "Kingston FURY 3200MHz 2x8",
            completeName: "RAM Kingston FURY DDR4 3200MHz 16GB 2x8GB",
            category: "Ram",
            price: "54 USD",
            image: "../img/11ram.webp",
            reviews: "(143)",
            total: "400",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/fury3200rgb/fury1.webp",
                "../img/pics/fury3200rgb/fury2.webp",
                "../img/pics/fury3200rgb/fury3.webp",
            ],
        },
        {
            id: 12,
            productName: "Corsair 2300MHz 2x8",
            completeName: "Corsair Vengeance LPX DDR4 2400MHz 16GB 2x8GB",
            category: "Ram",
            price: "45 USD",
            image: "../img/12ram.webp",
            reviews: "(5051)",
            total: "5700",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/corsair2400/corsair1.jpg",
                "../img/pics/corsair2400/corsair2.jpg",
                "../img/pics/corsair2400/corsair3.webp",
            ],
        },
        {
            id: 13,
            productName: "Razer Viper V3",
            completeName: "Razer Viper V3 HyperSpeed 30000 DPI",
            category: "Mouse",
            price: "110 USD",
            image: "../img/13mouse.jpg",
            reviews: "(95)",
            total: "120",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/razerviper3/viper1.webp",
                "../img/pics/razerviper3/viper2.webp",
                "../img/pics/razerviper3/viper3.webp",
            ],
        },
        {
            id: 14,
            productName: "HyperX Cloud Orbit S",
            completeName: "HyperX Cloud Orbit S - 3D Audio Head Tracking",
            category: "Headset",
            price: "362 USD",
            image: "../img/14head.jpg",
            reviews: "(22)",
            total: "30",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/hyperxclouds/cloud1.jpg",
                "../img/pics/hyperxclouds/cloud2.webp",
            ],
        },
        {
            id: 15,
            productName: "Thermaltake 600W 80 Plus",
            completeName: "Thermaltake Smart Series 600W SLI 80 Plus",
            category: "Power",
            price: "102 USD",
            image: "../img/15power.webp",
            reviews: "(13)",
            total: "17",
            svgLink: "../img/svg-stars.svg",
            images: [
                "../img/pics/thermaltake600/thermal1.jpg",
                "../img/pics/thermaltake600/thermal2.webp",
                "../img/pics/thermaltake600/thermal3.jpg",
            ],
        },
    ]
};

export { products };
