
let products = {
    data: [
        {
            id: 1,
            productName: "RTX 4070 TI",
            completeName: "ASUS GeForce TUF Gaming RTX 4070Ti 12GB",
            category: "graphicCard",
            price: "780 USD",
            image: "../img/3.webp",
            reviews: "(75)",
            total: "100",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 2,
            productName: "LOGITECH G PRO",
            completeName: "Logitech G PRO Lightweight Wireless",
            category: "mouse",
            price: "53 USD",
            image: "../img/2.webp",
            reviews: "(452)",
            total: "525",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 3,
            productName: "RX 7900 GRE",
            completeName: "Radeon RX 7900 GRE OC Edition 16GB GDDR6",
            category: "graphicCard",
            price: "590 USD",
            image: "../img/5.webp",
            reviews: "(105)",
            total: "133",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 4,
            productName: "LOGITECH G355",
            completeName: "Logitech G335 Wired Gaming Headset",
            category: "headset",
            price: "57 USD",
            image: "../img/1.webp",
            reviews: "(98)",
            total: "102",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 5,
            productName: "RYZEN 5 5600",
            completeName: "AMD Ryzen 5 5600 6-Core 3.5 GHz Socket AM4",
            category: "processor",
            price: "133 USD",
            image: "../img/6.webp",
            reviews: "(755)",
            total: "844",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 6,
            productName: "GT 1030",
            completeName: "GIGABYTE GeForce GT 1030 Low Profile D4 2G",
            category: "graphicCard",
            price: "64 USD",
            image: "../img/4.webp",
            reviews: "(34)",
            total: "65",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 7,
            productName: "Gigabyte B450 V2",
            completeName: "Gigabyte B450 Aorus Elite V2",
            category: "motherboard",
            price: "117 USD",
            image: "../img/7mother.webp",
            reviews: "(560)",
            total: "720",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 8,
            productName: "MSI B760 PLUS",
            completeName: "MSI B760 GAMING PLUS",
            category: "motherboard",
            price: "163 USD",
            image: "../img/8mother.jpg",
            reviews: "(265)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 9,
            productName: "Intel I5-21400F",
            completeName: "I5-12400F - 6-Core 2.5 GHz - LGA 1700",
            category: "processor",
            price: "133 USD",
            image: "../img/9proc.webp",
            reviews: "(1575)",
            total: "1800",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 10,
            productName: "Intel I7-13700K",
            completeName: "i7-13700K - 16-Core 3.4 GHz - LGA 1700",
            category: "processor",
            price: "389 USD",
            image: "../img/10core.webp",
            reviews: "(262)",
            total: "300",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 11,
            productName: "Kingston FURY 3200MHz 2x8",
            completeName: "RAM Kingston FURY DDR4 3200MHz 16GB 2x8GB",
            category: "ram",
            price: "54 USD",
            image: "../img/11ram.webp",
            reviews: "(143)",
            total: "400",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 12,
            productName: "Corsair 2300MHz 2x8",
            completeName: "Corsair Vengeance LPX DDR4 2400MHz 16GB 2x8GB",
            category: "ram",
            price: "45 USD",
            image: "../img/12ram.webp",
            reviews: "(5051)",
            total: "5700",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 13,
            productName: "Razer Viper V3",
            completeName: "Razer Viper V3 HyperSpeed 30000 DPI",
            category: "mouse",
            price: "110 USD",
            image: "../img/13mouse.jpg",
            reviews: "(95)",
            total: "120",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 14,
            productName: "HyperX Cloud Orbit S",
            completeName: "HyperX Cloud Orbit S - 3D Audio Head Tracking",
            category: "headset",
            price: "362 USD",
            image: "../img/14head.jpg",
            reviews: "(22)",
            total: "30",
            svgLink: "../img/svg-stars.svg",
        },
        {
            id: 15,
            productName: "Thermaltake 600W 80 Plus",
            completeName: "Thermaltake Smart Series 600W SLI 80 Plus",
            category: "power",
            price: "102 USD",
            image: "../img/15power.webp",
            reviews: "(13)",
            total: "17",
            svgLink: "../img/svg-stars.svg",
        },
    ]
};

export { products };
